### ISSUE TITLE
Display file at point when using deft-find-file

### ISSUE THREAD

**Issue by AtomicNess123** [jrblevin/deft#109]
Hi, I'm not sure if this is possible. When I use deft-find-file and get a list of all my files, it would be very useful to preview, as one moves up and down the arrow keys, the file at point displayed in the side window. This way we can be sure to select the file we are searching for more efficiently. Thanks!

**Comment by EFLS** [comment]
If this is the same use case as the [issue you opened in Zetteldeft](https://github.com/EFLS/zetteldeft/issues/132), please close this one as well.

For sake of completeness, this is the answer I suggested there:
>  Call Deft, enter your search query, move through the files, and use deft-open-file-other-window.
