### ISSUE TITLE
Create org notes by default

### ISSUE THREAD

**Issue by xin-jin** [jrblevin/deft#21]
Is it possible to create all new notes in org-mode (with .org file extension) by default?

**Comment by jrblevin** [comment]
Yes. The first element of `deft-extensions` is the default extension used to create new files. So, make sure "org" appears first. Example:

```lisp
(setq deft-extensions '("org" "txt" "tex"))
```

**Comment by xin-jin** [comment]
I see. Thanks!

Probably you could highlight that line ("The first element ...") in README, or add a short explanation for org-mode for people to search for... I searched a bit but didn't notice that line. I thought `deft-extensions` was only for setting which extensions to search for.
