### ISSUE TITLE
`RET` behavior after `deft-open-file-other-window`

### ISSUE THREAD

**Issue by xin-jin** [jrblevin/deft#22]
If I use `C-o` to open file in another window, then when I enter a file with `RET`, the window created by `C-o` is still present. Possible to change the behavior (or add as an option)? Usually I use `C-o` just to browse through files, and after `RET` a file, I expect the other window to be closed automatically.

**Comment by jrblevin** [comment]
Thanks for this suggestion. I can see your point, however, it's not clear that this should be the default behavior. Certainly not when one might have several windows open at once.

Given your workflow, when you're ready to open a file taking up the full frame you currently have two options (and both are short):

1. <kbd>C-o</kbd>, <kbd>C-x 0</kbd>
2. <kbd>RET</kbd>, <kbd>C-x 1</kbd>

**Comment by xin-jin** [comment]
Yes. I do know how to `delete-other-windows`. But an option or function to do this automatically would be nice. 

I know how to bind a key to do `RET` and `C-x 1` together, but do not know how to just close the window deft created. Do you think it possible?

**Comment by jrblevin** [comment]
Maybe `(delete-window (other-window 1))`?

**Comment by xin-jin** [comment]
Now I realize that a better option may be to use something like `other-window-scroll-buffer` to show a file in another window (I know little about lisp, but `company-mode` has a function `company-show-doc-buffer` that does this). Currently, `deft-open-file-other-window` seems to occupy one of the windows (and will not revert back to the original buffer when it is done).

**Comment by xin-jin** [comment]
Hmm, I take that back. I guess one better behavior of `deft-open-file-other-window` could be to create a new window rather than to occupy an existing window.

**Comment by jrblevin** [comment]
I'm closing this for now because I'm not sure what to do about this, if anything. If anyone would like to discuss specific ways to improve window handling with respect to <kbd>C-o</kbd> and <kbd>RET</kbd> while browsing files, feel free to comment here or submit a pull request.
