### ISSUE TITLE
deft-extensions and the deft-find-file extension

### ISSUE THREAD

**Issue by fooqri** [jrblevin/deft#23]
Thanks for *deft* I use it for all my notes!

I have a number of file types in my notes directory but I want deft to only look for .org files. The _deft-extensions_ variable works as advertised to filter the results in the main deft index view, but the _deft-find-file()_ function shows other file types like .md files that match the search string. Is that the intended behavior? Is there a variable to set to filter the  _deft-find-file()_  list also?

**Comment by jrblevin** [comment]
The previous behavior of considering *all* files in `deft-directory` was not quite intended.  `deft-find-file` was intended to act like `find-file`, but to limit consideration to files in `deft-directory`.  But as you point out, not all such files are indexed by Deft; some may have extensions not in `deft-extensions` and should be excluded when using `deft-find-file`.

I wasn't able to find a way to exclude files by regexp when using `read-file-name`, so I re-wrote `deft-find-file` using `completing-read` instead, provided with a pre-populated list of all files known to Deft.  Other types of files will not be listed.  Another benefit of using `completing-read` is that `deft-find-file` will read/complete filenames using ido, helm, etc. when enabled.
