### ISSUE TITLE
deft-open-file-hook is run outside of the context of the new buffer

### ISSUE THREAD

**Issue by harob** [jrblevin/deft#36]
Background: For convoluted reasons (all my notes have the .txt extension so Notational Velocity and iOS Simplenote will display them, but they are in org format) I want to be able to change the major mode of each note buffer when it is opened by deft. This used to be possible with the `deft-text-mode` var, but that was removed in d325df79e161337739bba0c992a05c9d12d8c2eb .

It seems like the `deft-open-file-hook` hook should be perfect for this, but as it is run outside of the `(with-current-buffer ...)` s-expr in `deft-open-file`, any mode changes (e.g. calling `(org-mode)`) don't actually apply to the newly opened note buffer.

Is that intentional? If not simply moving the `run-hooks` call inside the `(with-current-buffer ...)` block fixes the issue. I'm happy to submit a PR to that effect.

Thanks!

**Comment by jrblevin** [comment]
You may be right about the hook, I will check, but there is a simpler solution to the file extension issue using `auto-mode-alist` as discussed in #4.

**Comment by jrblevin** [comment]
The documentation for `find-file-hook` says "The buffer visiting the file is current when the hook functions are run." So, I suppose it makes sense for `deft-open-file-hook` to behave the same way. If you could submit a PR that would be great.
