### ISSUE TITLE
Feature request: Smarter note housekeeping (delete notes based on 'last time read')

### ISSUE THREAD

**Issue by asn-d6** [jrblevin/deft#38]
Hello,

I'm a big fan of deft, and through my years of use I have accumulated about 600 notes. Out of all those notes, most of them (400+) are ancient notes that I will never ever use in my life again. For example, I make quick notes all the time that I use once or twice and then they just rot there.

Having so many notes makes my deft home screen almost unuseable: it's very cluttered and also a bit slower to load.

What would be the right way to do notes housekeeping? I've been thinking that I could add a `(deft-housekeeping`) command that  deletes notes that haven't been read in over N months. So like, if I haven't opened a note for two years, it will delete it (or ask y/n to delete it).

Do you think such a thing would be useful, or in scope for deft? Or does it exist already?
Or should this be done as an emacs hook so that it's completely third party?

If this is not possible, how would you suggest I go around implementing this? (my elisp is subpar, but I can try)

**Comment by 0fiscalentropy** [comment]
If I'm not mistaken, this could be done by firstly checking the `atime` (date last opened) for all the files in the directory and then call `deft-archive-file` on the files that haven't been opened in the last N months.  Don't know much elisp, so wouldn't know exactly how to implement it in Emacs, but I could try a shell script (just move the matching files into `./archive`)

**Comment by asn-d6** [comment]
Thanks for the help! Closing this!
