### ISSUE TITLE
Remove title and display filter in mode-line

### ISSUE THREAD

**Issue by steckerhalter** [jrblevin/deft#39]
This is a suggestion. I usually work with the latest modified file so when I bring up Deft I have to move down two lines to the first file and press RET. How about removing the first two lines altogether and display the filter in the mode-line? Then the latest modified file would only be one RET away. I do not filter often and I think this would make sense, at least as an option if not as default.

**Comment by steckerhalter** [comment]
A quick implementation that is enough for me:

```cl
  (defun deft-print-header nil)
  (add-to-list 'mode-line-misc-info '(:eval (deft-whole-filter-regexp)))
```

**Comment by steckerhalter** [comment]
I like this even better (modifying the mode-name):

```cl
  (defun deft-print-header () (deft-set-mode-name))
  (defun deft-set-mode-name ()
    "Set the mode line text based on search mode and add the filter."
    (let* ((name (if deft-incremental-search "Deft" "Deft/R"))
           (filter (deft-whole-filter-regexp))
           (sep (unless (string= "" filter) "/")))
      (setq mode-name (concat name sep filter))))
```

**Comment by jrblevin** [comment]
Thanks for this suggestion and the code. Commit 957a53b changes the default point position to be the third line, which is the line representing the last modified file. I think that should address the main issue (wanting to reduce keystrokes).

I don't want to change Deft to use the modeline for the filter string at this point, but anyone who does can advise or redefine the functions as above to get that behavior.
