### ISSUE TITLE
Deft always creates new files with .txt extension

### ISSUE THREAD

**Issue by olegbc1** [jrblevin/deft#49]
It appears that despite the configuration, deft always saves files with .txt extension. 
Running Windows 10 and GNU Emacs 26.0.90 (build 3, x86_64-w64-mingw32) of 2017-10-13. Can you help me escape the corporate windows hell with emacs? :) 

My config below

```
;; notational velocity like package https://jblevins.org/projects/deft/
  (use-package deft
  :straight t)

;; setting default extensions for deft to search
(setq deft-text-mode 'org-mode)
(setq deft-directory "~/Dropbox/Oleg/Org/")
(setq deft-new-file-format "%Y-%m-%dT%H%M") ;; on windows files with ":"-symbol can't be saved, so this is editing format to save in a format without ":"
(setq deft-extensions '("org"))
  
;; making deft also search for files in subdirectories
(setq deft-recursive t)

(global-set-key [C-f12] 'deft) 
```

**Comment by jrblevin** [comment]
Can you try configuring it like this and let me know if it works?

``` emacs-lisp
(use-package deft
  :bind ("C-<f12>" . deft)
  :init (setq deft-directory "~/Dropbox/Oleg/Org/"
              deft-text-mode 'org-mode
              deft-extensions '("org")
              deft-recursive t
              deft-new-file-format "%Y-%m-%dT%H%M"))
```

Otherwise, you can try setting `deft-default-extension` directly.  It will default to the first value in `deft-extensions`, but for it to work that way the extensions list needs to be set before loading the package.

**Comment by olegbc1** [comment]
@jrblevin your code worked - thanks! Do you know why this was better?

**Comment by jrblevin** [comment]
Glad it worked!

With `use-package`, `:init` evaluates the code _before_ the package is loaded, so then when deft chooses the first element of `deft-extensions`, it's your custom list not the package default list (which begins with "txt").

**Comment by olegbc1** [comment]
Thanks! Just to clarify - shouldn't `(setq deft-extensions '("org"))` declared after `(use-package deft)` just override the the package defaults?

**Comment by jrblevin** [comment]
The code in the package works like this:

``` emacs-lisp
(defcustom deft-extensions '("txt" "text" "md" "markdown" "org"))
(defvar deft-default-extension (car deft-extensions))
```

So, for better or worse, `deft-default-extension` is currently defined relative to the value of `deft-extensions` at package load time. Perhaps I should use a function instead, so that the default extensions can change dynamically.

**Comment by olegbc1** [comment]
Got it, thanks! I'll flag this issue as closed.
Thanks for your work on these packages - deft, your themes and markdown mode are unbelievably useful!
