### ISSUE TITLE
If the deft browser buffer is killed, the next time you load deft, it takes longer -- and gets worse each time

### ISSUE THREAD

**Issue by termitereform** [jrblevin/deft#63]
So, I've noticed a weird problem with deft.

Some background and context. I'm in a situation where I'm dealing with hundreds of individual note files. Deft handles them like a champ when I limit the number of entries shown by the deft browser to something reasonable, and I've been impressed overall with how well it works. The below is my config:

`(use-package deft
  :ensure t
  :config
  (setq deft-default-extension "org")
  (setq deft-file-limit 32)
  (setq deft-filter-only-filenames nil)
  (setq deft-recursive nil)
  :commands (deft)
  :bind ("<f8>" . deft)
  :init
  )
(add-hook 'deft-mode-hook 
          (lambda ()
            (setq display-line-numbers nil)
            ))`

The problem is, if I kill the deft buffer and then re-open it, the length of time it hangs at "Deft initializing..." increases. On first load, it takes about half a second to initialize with 800 files in the deft directory. On second load, it's a little longer. On third load it's a second or two. On fourth load it's multiple seconds. And it just gets worse from there. 

No idea what's causing it. It's really weird!

**Comment by termitereform** [comment]
This was caused by using a non-standard `gc-cons-threshold` in my init.

**Comment by AtomicNess123** [comment]
On this same topic, what shall I add to my init to initialize deft and not wait when I need to create a note?
