### ISSUE TITLE
feature request: define template for all new 

### ISSUE THREAD

**Issue by elliottw** [jrblevin/deft#71]
For my particular use case, I'd like to create a template that defines the location for org-attach to be equal to the newly created file. Something like:

for 2019-11-22.org

* heading
:Properties:
:ATTACH_DIR: 2019-11-22
:ATTACH_DIR_INHERIT: t
:END:

**Comment by savagej** [comment]
https://org-roam.readthedocs.io/en/latest/templating/ would this help you out at all?

**Comment by elliottw** [comment]
yeah, i think i created the issue before templating existed.
