### ISSUE TITLE
deft-directory can't see any files

### ISSUE THREAD

**Issue by ambimorph** [jrblevin/deft#76]
When I first installed deft, I put
(setq deft-directory "~/notes/") in my .emacs file.
Deft sees nothing there when I start it, even if there are files there with the right extension, and even if they have previously been created via Deft.

If I create a file from Deft it puts it in that directory and sees it until I refresh and then it doesn't see anything again.

The same thing happens at ~/.deft if I don't change the default directory.

**Comment by ambimorph** [comment]
My bad -- I should have given more detail. I had a typo in the variable deft-entensions, so they immediately disappeared on refresh.

**Comment by vcg3rd** [comment]
I don't have a typo, and the same thing suddenly happened with me

`;; Deft
(require 'deft)
(setq deft-extensions '("org" "txt" "md")) 
(setq deft-default-extension "org")
(setq deft-directory "~/Dropbox/roam") 
(setq deft-recursive t) ;; Allows searching in subdirectories.
(global-set-key [f6] 'deft)
(global-set-key (kbd "C-x C-g") 'deft-find-file)`

f6 returns "No Files Found"
