### ISSUE TITLE
No need to escape quotes for replacement characters in `deft-file-naming-rules` (Emacs 24.4)

### ISSUE THREAD

**Issue by gsastry** [jrblevin/deft#9]
On Emacs 24.4, the code for `deft-file-naming-rules` breaks with `Symbol's function definition is void`. Removing the slashes used to escape quotes fixes it. 

(I don't know anything about Emacs, so I'm not submitted a PR. Not sure if this will break in previous versions...would be odd)

```elisp
(setq deft-use-filter-string-for-filename t)
(setq deft-file-naming-rules '((noslash . "-")
                               (nospace . "-")
                               (case-fn . downcase)))
```

**Comment by jrblevin** [comment]
Thanks! Fixed in a3e25d9.
