### ISSUE TITLE
creating new files with Deft using prompt for title

### ISSUE THREAD

**Issue by AtomicNess123** [jrblevin/deft#97]
Is it possible to have a prompt for a file name to which the date would be preprended? Or that is what zetteldeft is suppose to do? Thanks.

**Comment by EFLS** [comment]
> Or that is what zetteldeft is suppose to do?

While it's built on top of Deft, Zetteldeft is really a different package. I don't think your question is a good fit for the issues section of Deft. But yes, Zetteldeft does this

**Comment by AtomicNess123** [comment]
Apologies. I understand that creating a new note with deft creates a note with a predefined name and can't be asked in advance.

**Comment by EFLS** [comment]
Well you can, actually, use `deft-new-file-named`. Sorry, didn't think of that in my first answer. It doesn't have a keybinding by default. For those other things, prepending a date, check out Zetteldeft.

**Comment by AtomicNess123** [comment]
This is great, thanks!
